spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=garage
springdoc.swagger-ui.path=/swagger-ui
server.servlet.context-path=/api
logging.level.root=INFO
logging.level.com.example.garage=DEBUG
spring.cache.type=caffeine
spring.cache.cache-names=cars,carList
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=10m
