spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=garage
springdoc.swagger-ui.path=/swagger-ui
server.servlet.context-path=/api
logging.level.root=INFO
logging.level.com.example.garage=DEBUG